# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cargarProceso.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cargarProceso(object):
    def setupUi(self, cargarProceso):
        cargarProceso.setObjectName("cargarProceso")
        cargarProceso.resize(452, 629)
        self.centralwidget = QtWidgets.QWidget(cargarProceso)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 470, 91, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tamMem_2 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_2.setGeometry(QtCore.QRect(60, 150, 111, 41))
        self.tamMem_2.setObjectName("tamMem_2")
        self.spinBoxTamMemo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamMemo.setGeometry(QtCore.QRect(200, 160, 71, 41))
        self.spinBoxTamMemo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo.setObjectName("spinBoxTamMemo")
        self.btn_terminar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_terminar.setGeometry(QtCore.QRect(270, 470, 91, 28))
        self.btn_terminar.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_terminar.setObjectName("btn_terminar")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 470, 91, 28))
        self.pushButton_5.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.spinBoxTamMemo_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamMemo_4.setGeometry(QtCore.QRect(200, 300, 71, 41))
        self.spinBoxTamMemo_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo_4.setObjectName("spinBoxTamMemo_4")
        self.spinBoxTamMemo_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamMemo_2.setGeometry(QtCore.QRect(200, 230, 71, 41))
        self.spinBoxTamMemo_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo_2.setObjectName("spinBoxTamMemo_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.tamMem_8 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_8.setGeometry(QtCore.QRect(60, 210, 111, 41))
        self.tamMem_8.setObjectName("tamMem_8")
        self.lineEdit_rcpu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rcpu.setGeometry(QtCore.QRect(200, 360, 161, 41))
        self.lineEdit_rcpu.setObjectName("lineEdit_rcpu")
        self.tamSo_2 = QtWidgets.QLabel(self.centralwidget)
        self.tamSo_2.setGeometry(QtCore.QRect(60, 290, 111, 41))
        self.tamSo_2.setObjectName("tamSo_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 360, 81, 20))
        self.label_4.setObjectName("label_4")
        cargarProceso.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(cargarProceso)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 26))
        self.menubar.setObjectName("menubar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        cargarProceso.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(cargarProceso)
        self.statusbar.setObjectName("statusbar")
        cargarProceso.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(cargarProceso)
        QtCore.QMetaObject.connectSlotsByName(cargarProceso)

    def retranslateUi(self, cargarProceso):
        _translate = QtCore.QCoreApplication.translate
        cargarProceso.setWindowTitle(_translate("cargarProceso", "Cargar Proceso"))
        self.pushButton_4.setText(_translate("cargarProceso", "Agregar"))
        self.tamMem_2.setText(_translate("cargarProceso", "Arribo:"))
        self.btn_terminar.setText(_translate("cargarProceso", "Terminar"))
        self.pushButton_5.setText(_translate("cargarProceso", "Reiniciar"))
        self.label_7.setText(_translate("cargarProceso", "Proceso"))
        self.tamMem_8.setText(_translate("cargarProceso", "Prioridad:"))
        self.tamSo_2.setText(_translate("cargarProceso", "Tamano:"))
        self.label_4.setText(_translate("cargarProceso", "RCPU:"))
        self.menuAyuda.setTitle(_translate("cargarProceso", "Ayuda"))
