# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuracion1.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configuracion1(object):
    def setupUi(self, configuracion1):
        configuracion1.setObjectName("configuracion1")
        configuracion1.resize(609, 629)
        self.centralwidget = QtWidgets.QWidget(configuracion1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 430, 161, 20))
        self.label_2.setObjectName("label_2")
        self.radioButtonFija = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFija.setGeometry(QtCore.QRect(200, 430, 51, 20))
        self.radioButtonFija.setObjectName("radioButtonFija")
        self.spinBoxTamSo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamSo.setGeometry(QtCore.QRect(160, 370, 71, 41))
        self.spinBoxTamSo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamSo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamSo.setMaximum(5)
        self.spinBoxTamSo.setObjectName("spinBoxTamSo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 120, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tamMem = QtWidgets.QLabel(self.centralwidget)
        self.tamMem.setGeometry(QtCore.QRect(40, 250, 111, 41))
        self.tamMem.setObjectName("tamMem")
        self.spinBoxTamMemo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamMemo.setGeometry(QtCore.QRect(150, 250, 71, 41))
        self.spinBoxTamMemo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo.setObjectName("spinBoxTamMemo")
        self.tamMem_2 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_2.setGeometry(QtCore.QRect(40, 200, 81, 41))
        self.tamMem_2.setObjectName("tamMem_2")
        self.tamSo = QtWidgets.QLabel(self.centralwidget)
        self.tamSo.setGeometry(QtCore.QRect(40, 370, 111, 41))
        self.tamSo.setObjectName("tamSo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 320, 131, 20))
        self.label_3.setObjectName("label_3")
        self.selectAlg = QtWidgets.QComboBox(self.centralwidget)
        self.selectAlg.setGeometry(QtCore.QRect(180, 320, 171, 22))
        self.selectAlg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectAlg.setEditable(False)
        self.selectAlg.setObjectName("selectAlg")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.radioButtonVariable = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonVariable.setGeometry(QtCore.QRect(280, 430, 81, 20))
        self.radioButtonVariable.setObjectName("radioButtonVariable")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 210, 171, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonAceptarConf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAceptarConf.setGeometry(QtCore.QRect(90, 490, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonAceptarConf.setFont(font)
        self.pushButtonAceptarConf.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonAceptarConf.setObjectName("pushButtonAceptarConf")
        self.pushButtonAceptarConf_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAceptarConf_2.setGeometry(QtCore.QRect(250, 490, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonAceptarConf_2.setFont(font)
        self.pushButtonAceptarConf_2.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonAceptarConf_2.setObjectName("pushButtonAceptarConf_2")
        configuracion1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(configuracion1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 26))
        self.menubar.setObjectName("menubar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        configuracion1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(configuracion1)
        self.statusbar.setObjectName("statusbar")
        configuracion1.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(configuracion1)
        QtCore.QMetaObject.connectSlotsByName(configuracion1)

    def retranslateUi(self, configuracion1):
        _translate = QtCore.QCoreApplication.translate
        configuracion1.setWindowTitle(_translate("configuracion1", "Configuracion de Arranque"))
        self.label.setText(_translate("configuracion1", "Configuracion de Arranque"))
        self.label_2.setText(_translate("configuracion1", "Seleccione tipo de Particion"))
        self.radioButtonFija.setText(_translate("configuracion1", "Fija"))
        self.label_6.setText(_translate("configuracion1", "Crear Memoria"))
        self.tamMem.setText(_translate("configuracion1", "TamanoMemoria:"))
        self.tamMem_2.setText(_translate("configuracion1", "NombreConf:"))
        self.tamSo.setText(_translate("configuracion1", "TamanoSistOp:"))
        self.label_3.setText(_translate("configuracion1", "Seleccione Algoritmo"))
        self.selectAlg.setItemText(0, _translate("configuracion1", "BestFit"))
        self.selectAlg.setItemText(1, _translate("configuracion1", "FirstFit"))
        self.selectAlg.setItemText(2, _translate("configuracion1", "Worstfit"))
        self.radioButtonVariable.setText(_translate("configuracion1", "Variable"))
        self.pushButtonAceptarConf.setText(_translate("configuracion1", "Aceptar"))
        self.pushButtonAceptarConf_2.setText(_translate("configuracion1", "Reiniciar"))
        self.menuAyuda.setTitle(_translate("configuracion1", "Ayuda"))
