# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuracion1.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configuracion1(object):
    def setupUi(self, configuracion1):
        configuracion1.setObjectName("configuracion1")
        self.centralwidget = QtWidgets.QWidget(configuracion1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 731, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 290, 161, 20))
        self.label_2.setObjectName("label_2")
        self.radioButtonFija = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFija.setGeometry(QtCore.QRect(580, 290, 51, 20))
        self.radioButtonFija.setObjectName("radioButtonFija")
        self.spinBoxTamSo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamSo.setGeometry(QtCore.QRect(690, 220, 71, 41))
        self.spinBoxTamSo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamSo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamSo.setMaximum(5)
        self.spinBoxTamSo.setObjectName("spinBoxTamSo")
        self.tamMem_9 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_9.setGeometry(QtCore.QRect(80, 340, 151, 41))
        self.tamMem_9.setObjectName("tamMem_9")
        self.spinBoxNumPart = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNumPart.setGeometry(QtCore.QRect(240, 340, 71, 41))
        self.spinBoxNumPart.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxNumPart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNumPart.setMaximum(5)
        self.spinBoxNumPart.setObjectName("spinBoxNumPart")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 140, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tamMem = QtWidgets.QLabel(self.centralwidget)
        self.tamMem.setGeometry(QtCore.QRect(340, 220, 111, 41))
        self.tamMem.setObjectName("tamMem")
        self.spinBoxTamMemo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamMemo.setGeometry(QtCore.QRect(450, 220, 71, 41))
        self.spinBoxTamMemo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo.setObjectName("spinBoxTamMemo")
        self.tamMem_2 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_2.setGeometry(QtCore.QRect(80, 220, 81, 41))
        self.tamMem_2.setObjectName("tamMem_2")
        self.tamSo = QtWidgets.QLabel(self.centralwidget)
        self.tamSo.setGeometry(QtCore.QRect(570, 220, 111, 41))
        self.tamSo.setObjectName("tamSo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 290, 131, 20))
        self.label_3.setObjectName("label_3")
        self.selectAlg = QtWidgets.QComboBox(self.centralwidget)
        self.selectAlg.setGeometry(QtCore.QRect(210, 290, 171, 22))
        self.selectAlg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectAlg.setEditable(False)
        self.selectAlg.setObjectName("selectAlg")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.radioButtonVariable = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonVariable.setGeometry(QtCore.QRect(660, 290, 81, 20))
        self.radioButtonVariable.setObjectName("radioButtonVariable")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 230, 171, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.spinBoxNumPart_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNumPart_2.setGeometry(QtCore.QRect(570, 340, 71, 41))
        self.spinBoxNumPart_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxNumPart_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNumPart_2.setMaximum(5)
        self.spinBoxNumPart_2.setObjectName("spinBoxNumPart_2")
        self.tamMem_11 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_11.setGeometry(QtCore.QRect(660, 340, 61, 41))
        self.tamMem_11.setObjectName("tamMem_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 340, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.tamMem_10 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_10.setGeometry(QtCore.QRect(490, 340, 91, 41))
        self.tamMem_10.setObjectName("tamMem_10")
        self.spinBoxNumPart_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNumPart_3.setGeometry(QtCore.QRect(730, 340, 71, 41))
        self.spinBoxNumPart_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxNumPart_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNumPart_3.setMaximum(5)
        self.spinBoxNumPart_3.setObjectName("spinBoxNumPart_3")
        self.pushButtonAceptarConf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAceptarConf.setGeometry(QtCore.QRect(130, 460, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonAceptarConf.setFont(font)
        self.pushButtonAceptarConf.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonAceptarConf.setObjectName("pushButtonAceptarConf")
        self.pushButtonAceptarConf_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAceptarConf_2.setGeometry(QtCore.QRect(420, 460, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonAceptarConf_2.setFont(font)
        self.pushButtonAceptarConf_2.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonAceptarConf_2.setObjectName("pushButtonAceptarConf_2")
        configuracion1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(configuracion1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 26))
        self.menubar.setObjectName("menubar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        configuracion1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(configuracion1)
        self.statusbar.setObjectName("statusbar")
        configuracion1.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(configuracion1)
        QtCore.QMetaObject.connectSlotsByName(configuracion1)

    def retranslateUi(self, configuracion1):
        _translate = QtCore.QCoreApplication.translate
        configuracion1.setWindowTitle(_translate("configuracion1", "MainWindow"))
        self.label.setText(_translate("configuracion1", "Configuracion de Arranque"))
        self.label_2.setText(_translate("configuracion1", "Seleccione tipo de Particion"))
        self.radioButtonFija.setText(_translate("configuracion1", "Fija"))
        self.tamMem_9.setText(_translate("configuracion1", "NumeroParticiones fijas:"))
        self.label_6.setText(_translate("configuracion1", "Crear Memoria"))
        self.tamMem.setText(_translate("configuracion1", "TamanoMemoria:"))
        self.tamMem_2.setText(_translate("configuracion1", "NombreConf:"))
        self.tamSo.setText(_translate("configuracion1", "TamanoSistOp:"))
        self.label_3.setText(_translate("configuracion1", "Seleccione Algoritmo"))
        self.selectAlg.setItemText(0, _translate("configuracion1", "BestFit"))
        self.selectAlg.setItemText(1, _translate("configuracion1", "FirstFit"))
        self.selectAlg.setItemText(2, _translate("configuracion1", "Worstfit"))
        self.radioButtonVariable.setText(_translate("configuracion1", "Variable"))
        self.tamMem_11.setText(_translate("configuracion1", "PuntoFin:"))
        self.label_7.setText(_translate("configuracion1", "Particion Fija"))
        self.tamMem_10.setText(_translate("configuracion1", "PuntoInicion:"))
        self.pushButtonAceptarConf.setText(_translate("configuracion1", "Aceptar"))
        self.pushButtonAceptarConf_2.setText(_translate("configuracion1", "Reiniciar"))
        self.menuAyuda.setTitle(_translate("configuracion1", "Ayuda"))
