# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuracion1.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configuracion1(object):
    def setupUi(self, configuracion1):
        configuracion1.setObjectName("configuracion1")
        configuracion1.resize(504, 629)
        self.centralwidget = QtWidgets.QWidget(configuracion1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 451, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 390, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.radioButtonFija = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonFija.setGeometry(QtCore.QRect(280, 390, 51, 20))
        self.radioButtonFija.setObjectName("radioButtonFija")
        self.spinBoxTamSo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamSo.setGeometry(QtCore.QRect(270, 340, 71, 41))
        self.spinBoxTamSo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamSo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamSo.setMinimum(5)
        self.spinBoxTamSo.setMaximum(35)
        self.spinBoxTamSo.setObjectName("spinBoxTamSo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 100, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tamMem = QtWidgets.QLabel(self.centralwidget)
        self.tamMem.setGeometry(QtCore.QRect(20, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tamMem.setFont(font)
        self.tamMem.setObjectName("tamMem")
        self.spinBoxTamMemo = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxTamMemo.setGeometry(QtCore.QRect(260, 210, 71, 41))
        self.spinBoxTamMemo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo.setMinimum(50)
        self.spinBoxTamMemo.setObjectName("spinBoxTamMemo")
        self.tamMem_2 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_2.setGeometry(QtCore.QRect(20, 160, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tamMem_2.setFont(font)
        self.tamMem_2.setObjectName("tamMem_2")
        self.tamSo = QtWidgets.QLabel(self.centralwidget)
        self.tamSo.setGeometry(QtCore.QRect(20, 330, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tamSo.setFont(font)
        self.tamSo.setObjectName("tamSo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 280, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.selectAlg = QtWidgets.QComboBox(self.centralwidget)
        self.selectAlg.setGeometry(QtCore.QRect(250, 280, 171, 22))
        self.selectAlg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectAlg.setEditable(False)
        self.selectAlg.setObjectName("selectAlg")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.radioButtonVariable = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonVariable.setGeometry(QtCore.QRect(360, 390, 81, 20))
        self.radioButtonVariable.setObjectName("radioButtonVariable")
        self.lineEdit_Nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Nombre.setGeometry(QtCore.QRect(250, 170, 171, 22))
        self.lineEdit_Nombre.setObjectName("lineEdit_Nombre")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(120, 520, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_aceptar.setFont(font)
        self.btn_aceptar.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.btn_reiniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reiniciar.setGeometry(QtCore.QRect(280, 520, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.btn_reiniciar.setFont(font)
        self.btn_reiniciar.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_reiniciar.setObjectName("btn_reiniciar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 350, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.spinBox_cantParticion = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cantParticion.setGeometry(QtCore.QRect(270, 440, 71, 41))
        self.spinBox_cantParticion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_cantParticion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_cantParticion.setMinimum(1)
        self.spinBox_cantParticion.setMaximum(50)
        self.spinBox_cantParticion.setObjectName("spinBox_cantParticion")
        self.tamMem_10 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_10.setGeometry(QtCore.QRect(30, 440, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tamMem_10.setFont(font)
        self.tamMem_10.setObjectName("tamMem_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 220, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        configuracion1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(configuracion1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 26))
        self.menubar.setObjectName("menubar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        configuracion1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(configuracion1)
        self.statusbar.setObjectName("statusbar")
        configuracion1.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(configuracion1)
        QtCore.QMetaObject.connectSlotsByName(configuracion1)

    def retranslateUi(self, configuracion1):
        _translate = QtCore.QCoreApplication.translate
        configuracion1.setWindowTitle(_translate("configuracion1", "Crear Memoria"))
        self.label.setText(_translate("configuracion1", "Configuracion de Arranque"))
        self.label_2.setText(_translate("configuracion1", "Seleccione tipo de Particion"))
        self.radioButtonFija.setText(_translate("configuracion1", "Fija"))
        self.label_6.setText(_translate("configuracion1", "Crear Memoria"))
        self.tamMem.setText(_translate("configuracion1", "TamanoMemoria:"))
        self.tamMem_2.setText(_translate("configuracion1", "Nombre de Configuracion:"))
        self.tamSo.setText(_translate("configuracion1", "Tamaño Sistema Operativo:"))
        self.label_3.setText(_translate("configuracion1", " Algoritmo de Planificacion:"))
        self.selectAlg.setItemText(0, _translate("configuracion1", "BestFit"))
        self.selectAlg.setItemText(1, _translate("configuracion1", "FirstFit"))
        self.selectAlg.setItemText(2, _translate("configuracion1", "Worstfit"))
        self.radioButtonVariable.setText(_translate("configuracion1", "Variable"))
        self.btn_aceptar.setText(_translate("configuracion1", "Aceptar"))
        self.btn_reiniciar.setText(_translate("configuracion1", "Reiniciar"))
        self.label_4.setText(_translate("configuracion1", "%"))
        self.tamMem_10.setText(_translate("configuracion1", "Cantidad Particion:"))
        self.label_5.setText(_translate("configuracion1", "Kb"))
        self.menuAyuda.setTitle(_translate("configuracion1", "Ayuda"))
