# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuracion.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuracion(object):
    def setupUi(self, Configuracion):
        Configuracion.setObjectName("Configuracion")
        Configuracion.resize(938, 764)
        self.centralwidget = QtWidgets.QWidget(Configuracion)
        self.centralwidget.setObjectName("centralwidget")
        self.contenedor = QtWidgets.QFrame(self.centralwidget)
        self.contenedor.setGeometry(QtCore.QRect(30, 20, 841, 641))
        self.contenedor.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.formularioTerminar = QtWidgets.QFrame(self.contenedor)
        self.formularioTerminar.setGeometry(QtCore.QRect(10, 60, 371, 561))
        self.formularioTerminar.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border-color: rgb(0, 0, 0);")
        self.formularioTerminar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formularioTerminar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formularioTerminar.setObjectName("formularioTerminar")
        self.tamMem = QtWidgets.QLabel(self.formularioTerminar)
        self.tamMem.setGeometry(QtCore.QRect(10, 145, 111, 41))
        self.tamMem.setObjectName("tamMem")
        self.tamSo = QtWidgets.QLabel(self.formularioTerminar)
        self.tamSo.setGeometry(QtCore.QRect(10, 200, 111, 41))
        self.tamSo.setObjectName("tamSo")
        self.selectAlg = QtWidgets.QComboBox(self.formularioTerminar)
        self.selectAlg.setGeometry(QtCore.QRect(30, 310, 171, 22))
        self.selectAlg.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectAlg.setEditable(False)
        self.selectAlg.setObjectName("selectAlg")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.selectAlg.addItem("")
        self.radioButtonFija = QtWidgets.QRadioButton(self.formularioTerminar)
        self.radioButtonFija.setGeometry(QtCore.QRect(50, 390, 51, 20))
        self.radioButtonFija.setObjectName("radioButtonFija")
        self.radioButtonVariable = QtWidgets.QRadioButton(self.formularioTerminar)
        self.radioButtonVariable.setGeometry(QtCore.QRect(130, 390, 81, 20))
        self.radioButtonVariable.setObjectName("radioButtonVariable")
        self.label = QtWidgets.QLabel(self.formularioTerminar)
        self.label.setGeometry(QtCore.QRect(20, 350, 161, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.formularioTerminar)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 161, 20))
        self.label_2.setObjectName("label_2")
        self.spinBoxTamMemo = QtWidgets.QSpinBox(self.formularioTerminar)
        self.spinBoxTamMemo.setGeometry(QtCore.QRect(141, 160, 71, 41))
        self.spinBoxTamMemo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamMemo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamMemo.setObjectName("spinBoxTamMemo")
        self.spinBoxTamSo = QtWidgets.QSpinBox(self.formularioTerminar)
        self.spinBoxTamSo.setGeometry(QtCore.QRect(140, 210, 71, 41))
        self.spinBoxTamSo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxTamSo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTamSo.setMaximum(5)
        self.spinBoxTamSo.setObjectName("spinBoxTamSo")
        self.pushButtonAceptarConf = QtWidgets.QPushButton(self.formularioTerminar)
        self.pushButtonAceptarConf.setGeometry(QtCore.QRect(40, 510, 93, 28))
        self.pushButtonAceptarConf.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonAceptarConf.setObjectName("pushButtonAceptarConf")
        self.pushButtonReiniciarConf = QtWidgets.QPushButton(self.formularioTerminar)
        self.pushButtonReiniciarConf.setGeometry(QtCore.QRect(210, 510, 93, 28))
        self.pushButtonReiniciarConf.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonReiniciarConf.setObjectName("pushButtonReiniciarConf")
        self.tamMem_2 = QtWidgets.QLabel(self.formularioTerminar)
        self.tamMem_2.setGeometry(QtCore.QRect(10, 100, 111, 41))
        self.tamMem_2.setObjectName("tamMem_2")
        self.lineNombre = QtWidgets.QLineEdit(self.formularioTerminar)
        self.lineNombre.setGeometry(QtCore.QRect(90, 110, 251, 22))
        self.lineNombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineNombre.setObjectName("lineNombre")
        self.label_6 = QtWidgets.QLabel(self.formularioTerminar)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tamMem_9 = QtWidgets.QLabel(self.formularioTerminar)
        self.tamMem_9.setGeometry(QtCore.QRect(30, 430, 111, 41))
        self.tamMem_9.setObjectName("tamMem_9")
        self.spinBoxNumPart = QtWidgets.QSpinBox(self.formularioTerminar)
        self.spinBoxNumPart.setGeometry(QtCore.QRect(170, 440, 71, 41))
        self.spinBoxNumPart.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxNumPart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNumPart.setMaximum(5)
        self.spinBoxNumPart.setObjectName("spinBoxNumPart")
        self.label_5 = QtWidgets.QLabel(self.contenedor)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 841, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formularioTerminar_2 = QtWidgets.QFrame(self.contenedor)
        self.formularioTerminar_2.setGeometry(QtCore.QRect(430, 60, 371, 561))
        self.formularioTerminar_2.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border-color: rgb(0, 0, 0);")
        self.formularioTerminar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.formularioTerminar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formularioTerminar_2.setObjectName("formularioTerminar_2")
        self.tamMem_6 = QtWidgets.QLabel(self.formularioTerminar_2)
        self.tamMem_6.setGeometry(QtCore.QRect(20, 110, 111, 41))
        self.tamMem_6.setObjectName("tamMem_6")
        self.tamMem_7 = QtWidgets.QLabel(self.formularioTerminar_2)
        self.tamMem_7.setGeometry(QtCore.QRect(20, 140, 111, 41))
        self.tamMem_7.setObjectName("tamMem_7")
        self.tamMem_8 = QtWidgets.QLabel(self.formularioTerminar_2)
        self.tamMem_8.setGeometry(QtCore.QRect(20, 170, 111, 41))
        self.tamMem_8.setObjectName("tamMem_8")
        self.tamMem_10 = QtWidgets.QLabel(self.formularioTerminar_2)
        self.tamMem_10.setGeometry(QtCore.QRect(30, 230, 111, 41))
        self.tamMem_10.setObjectName("tamMem_10")
        self.spinBoxNumPart_2 = QtWidgets.QSpinBox(self.formularioTerminar_2)
        self.spinBoxNumPart_2.setGeometry(QtCore.QRect(170, 240, 71, 41))
        self.spinBoxNumPart_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxNumPart_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNumPart_2.setMaximum(5)
        self.spinBoxNumPart_2.setObjectName("spinBoxNumPart_2")
        self.tamMem_11 = QtWidgets.QLabel(self.formularioTerminar_2)
        self.tamMem_11.setGeometry(QtCore.QRect(30, 310, 111, 41))
        self.tamMem_11.setObjectName("tamMem_11")
        self.spinBoxNumPart_3 = QtWidgets.QSpinBox(self.formularioTerminar_2)
        self.spinBoxNumPart_3.setGeometry(QtCore.QRect(170, 320, 71, 41))
        self.spinBoxNumPart_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBoxNumPart_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNumPart_3.setMaximum(5)
        self.spinBoxNumPart_3.setObjectName("spinBoxNumPart_3")
        self.pushButtonReiniciarConf_2 = QtWidgets.QPushButton(self.formularioTerminar_2)
        self.pushButtonReiniciarConf_2.setGeometry(QtCore.QRect(140, 510, 93, 28))
        self.pushButtonReiniciarConf_2.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonReiniciarConf_2.setObjectName("pushButtonReiniciarConf_2")
        self.pushButtonAceptarConf_2 = QtWidgets.QPushButton(self.formularioTerminar_2)
        self.pushButtonAceptarConf_2.setGeometry(QtCore.QRect(20, 510, 93, 28))
        self.pushButtonAceptarConf_2.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonAceptarConf_2.setObjectName("pushButtonAceptarConf_2")
        self.pushButtonReiniciarConf_5 = QtWidgets.QPushButton(self.formularioTerminar_2)
        self.pushButtonReiniciarConf_5.setGeometry(QtCore.QRect(260, 510, 93, 28))
        self.pushButtonReiniciarConf_5.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.pushButtonReiniciarConf_5.setObjectName("pushButtonReiniciarConf_5")
        self.label_7 = QtWidgets.QLabel(self.formularioTerminar_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        Configuracion.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Configuracion)
        self.statusbar.setObjectName("statusbar")
        Configuracion.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Configuracion)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 938, 26))
        self.menuBar.setObjectName("menuBar")
        Configuracion.setMenuBar(self.menuBar)

        self.retranslateUi(Configuracion)
        QtCore.QMetaObject.connectSlotsByName(Configuracion)

    def retranslateUi(self, Configuracion):
        _translate = QtCore.QCoreApplication.translate
        Configuracion.setWindowTitle(_translate("Configuracion", "MainWindow"))
        self.tamMem.setText(_translate("Configuracion", "TamanoMemoria:"))
        self.tamSo.setText(_translate("Configuracion", "TamanoSistOp:"))
        self.selectAlg.setItemText(0, _translate("Configuracion", "Seleccione algoritmo"))
        self.selectAlg.setItemText(1, _translate("Configuracion", "BestFit"))
        self.selectAlg.setItemText(2, _translate("Configuracion", "FirstFit"))
        self.selectAlg.setItemText(3, _translate("Configuracion", "Worstfit"))
        self.radioButtonFija.setText(_translate("Configuracion", "Fija"))
        self.radioButtonVariable.setText(_translate("Configuracion", "Variable"))
        self.label.setText(_translate("Configuracion", "Seleccione tipo de Particion"))
        self.label_2.setText(_translate("Configuracion", "Seleccione Algoritmo"))
        self.pushButtonAceptarConf.setText(_translate("Configuracion", "Aceptar"))
        self.pushButtonReiniciarConf.setText(_translate("Configuracion", "Reiniciar"))
        self.tamMem_2.setText(_translate("Configuracion", "NombreConf:"))
        self.label_6.setText(_translate("Configuracion", "Memoria"))
        self.tamMem_9.setText(_translate("Configuracion", "NumeroParticiones:"))
        self.label_5.setText(_translate("Configuracion", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Configuracion de Arranque</span></p></body></html>"))
        self.tamMem_6.setText(_translate("Configuracion", "NombreConf:"))
        self.tamMem_7.setText(_translate("Configuracion", "TipoParticion:"))
        self.tamMem_8.setText(_translate("Configuracion", "MemoriaRestante:"))
        self.tamMem_10.setText(_translate("Configuracion", "PuntoInicion:"))
        self.tamMem_11.setText(_translate("Configuracion", "PuntoFin:"))
        self.pushButtonReiniciarConf_2.setText(_translate("Configuracion", "Reiniciar"))
        self.pushButtonAceptarConf_2.setText(_translate("Configuracion", "Agregar"))
        self.pushButtonReiniciarConf_5.setText(_translate("Configuracion", "Terminar"))
        self.label_7.setText(_translate("Configuracion", "Particion"))
