# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'particionFija.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParticionFija(object):
    def setupUi(self, ParticionFija):
        ParticionFija.setObjectName("ParticionFija")
        ParticionFija.resize(461, 629)
        self.centralwidget = QtWidgets.QWidget(ParticionFija)
        self.centralwidget.setObjectName("centralwidget")
        self.tamMem_6 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_6.setGeometry(QtCore.QRect(20, 70, 91, 41))
        self.tamMem_6.setObjectName("tamMem_6")
        self.btn_terminar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_terminar.setGeometry(QtCore.QRect(290, 500, 93, 28))
        self.btn_terminar.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_terminar.setObjectName("btn_terminar")
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(40, 500, 93, 28))
        self.btn_agregar.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_agregar.setObjectName("btn_agregar")
        self.tamMem_8 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_8.setGeometry(QtCore.QRect(20, 110, 111, 41))
        self.tamMem_8.setObjectName("tamMem_8")
        self.tamMem_11 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_11.setGeometry(QtCore.QRect(20, 270, 111, 41))
        self.tamMem_11.setObjectName("tamMem_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btn_reiniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reiniciar.setGeometry(QtCore.QRect(170, 500, 93, 28))
        self.btn_reiniciar.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_reiniciar.setObjectName("btn_reiniciar")
        self.sB_tamParticion = QtWidgets.QSpinBox(self.centralwidget)
        self.sB_tamParticion.setGeometry(QtCore.QRect(140, 280, 71, 41))
        self.sB_tamParticion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sB_tamParticion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sB_tamParticion.setMinimum(1)
        self.sB_tamParticion.setMaximum(99)
        self.sB_tamParticion.setObjectName("sB_tamParticion")
        self.label_NombreConf = QtWidgets.QLabel(self.centralwidget)
        self.label_NombreConf.setGeometry(QtCore.QRect(150, 80, 141, 21))
        self.label_NombreConf.setObjectName("label_NombreConf")
        self.label_MemoriaRes = QtWidgets.QLabel(self.centralwidget)
        self.label_MemoriaRes.setGeometry(QtCore.QRect(150, 120, 141, 21))
        self.label_MemoriaRes.setObjectName("label_MemoriaRes")
        self.tamMem_10 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_10.setGeometry(QtCore.QRect(20, 160, 111, 41))
        self.tamMem_10.setObjectName("tamMem_10")
        self.tamMem_12 = QtWidgets.QLabel(self.centralwidget)
        self.tamMem_12.setGeometry(QtCore.QRect(20, 210, 111, 41))
        self.tamMem_12.setObjectName("tamMem_12")
        self.tW_ParticionFija = QtWidgets.QTableWidget(self.centralwidget)
        self.tW_ParticionFija.setGeometry(QtCore.QRect(80, 340, 281, 101))
        self.tW_ParticionFija.setColumnCount(2)
        self.tW_ParticionFija.setObjectName("tW_ParticionFija")
        self.tW_ParticionFija.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tW_ParticionFija.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tW_ParticionFija.setHorizontalHeaderItem(1, item)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 290, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        ParticionFija.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ParticionFija)
        self.statusbar.setObjectName("statusbar")
        ParticionFija.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(ParticionFija)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 461, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuAyuda = QtWidgets.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        ParticionFija.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(ParticionFija)
        QtCore.QMetaObject.connectSlotsByName(ParticionFija)

    def retranslateUi(self, ParticionFija):
        _translate = QtCore.QCoreApplication.translate
        ParticionFija.setWindowTitle(_translate("ParticionFija", "Particion Fija"))
        self.tamMem_6.setText(_translate("ParticionFija", "NombreConf:"))
        self.btn_terminar.setText(_translate("ParticionFija", "Terminar"))
        self.btn_agregar.setText(_translate("ParticionFija", "Agregar"))
        self.tamMem_8.setText(_translate("ParticionFija", "MemoriaRestante:"))
        self.tamMem_11.setText(_translate("ParticionFija", "Tamaño Particion:"))
        self.label_7.setText(_translate("ParticionFija", "Particion Fija"))
        self.btn_reiniciar.setText(_translate("ParticionFija", "Reiniciar"))
        self.label_NombreConf.setText(_translate("ParticionFija", "TextLabel"))
        self.label_MemoriaRes.setText(_translate("ParticionFija", "TextLabel"))
        self.tamMem_10.setText(_translate("ParticionFija", "Cantidad Particion:"))
        self.tamMem_12.setText(_translate("ParticionFija", "Numero Particion:"))
        item = self.tW_ParticionFija.horizontalHeaderItem(0)
        item.setText(_translate("ParticionFija", "Id"))
        item = self.tW_ParticionFija.horizontalHeaderItem(1)
        item.setText(_translate("ParticionFija", "Tamano"))
        self.label_5.setText(_translate("ParticionFija", "Kb"))
        self.menuAyuda.setTitle(_translate("ParticionFija", "Ayuda"))
