# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outputwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OutputWindow(object):
    def setupUi(self, OutputWindow):
        OutputWindow.setObjectName("OutputWindow")
        OutputWindow.resize(800, 600)
        OutputWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(OutputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(386, 20, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 110, 771, 191))
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 350, 771, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(15, 0, 741, 161))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 1, 761, 201))
        self.tableWidget_2.setRowCount(8)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 320, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        OutputWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OutputWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        OutputWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OutputWindow)
        self.statusbar.setObjectName("statusbar")
        OutputWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OutputWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OutputWindow)

    def retranslateUi(self, OutputWindow):
        _translate = QtCore.QCoreApplication.translate
        OutputWindow.setWindowTitle(_translate("OutputWindow", "OutputWindow"))
        self.label.setText(_translate("OutputWindow", "Salida"))
        self.label_2.setText(_translate("OutputWindow", "Diagrama de Gantt"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("OutputWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("OutputWindow", "Tamano"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("OutputWindow", "Prioridad"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("OutputWindow", "T.Arribo"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("OutputWindow", "T.Fin"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("OutputWindow", "Particion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OutputWindow", "Procesos"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("OutputWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("OutputWindow", "Tamano"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("OutputWindow", "RegInf"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("OutputWindow", "RegSup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OutputWindow", "Particiones"))
        self.label_3.setText(_translate("OutputWindow", "Tablas"))


